### ISSUE TITLE
Composer file with altered ports gives errors

### ISSUE THREAD

**Issue by mcf-rocks** [AcalaNetwork/bodhi.js#622]
Do you know why this composer file does not work?

It's the example file, just with changed port numbers.

Are there hardcoded port numbers in the images?

The composer file:
```
# cat ./docker-compose-acala.yml 
services:
  acala-mandala-node:
    image: ghcr.io/acalanetwork/mandala-node:sha-f045637
    container_name: acala-mandala-node
    ports:
      - 4444:4444
    command:
      - --dev
      # - -lruntime=debug
      # - -levm=debug
      - --ws-port=4444
      - --ws-external
      - --rpc-port=4433
      - --rpc-external
      - --rpc-cors=all
      - --rpc-methods=unsafe
      #- --instant-sealing
  acala-postgres:
    image: postgres:12-alpine
    container_name: acala-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/mnt/big1/POSTGRES_ACALA
    environment:
      POSTGRES_PASSWORD: postgres

  acala-subquery-node:
    image: acala/evm-subql:c65f9c3
    container_name: acala-subquery-node
    ports:
      - 4400:4400
    depends_on:
      - acala-postgres
      - acala-mandala-node
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: host.docker.internal
      DB_PORT: 5432
    command:
      - -f=project.yaml
      - --network-endpoint=ws://acala-mandala-node:4444
      - --db-schema=acala_evm
      - --log-level=debug
      - --unsafe
      - --disable-historical

  acala-graphql-engine:
    image: onfinality/subql-query:v1.4.0
    container_name: acala-graphql-engine
    ports:
      - 4401:4401
    depends_on:
      - acala-postgres
      - acala-subquery-node
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      PORT: 4401
    command:
      - --name=acala_evm
      - --playground
      - --indexer=http://subquery-node:4400

  acala-eth-rpc-adapter-server:
    image: acala/eth-rpc-adapter:c65f9c3
    container_name: acala-eth-rpc-adapter-server
    restart: always
    depends_on:
      - acala-mandala-node
      - acala-subquery-node
      - acala-graphql-engine
    ports:
      - 4402:4402
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - SUBQL_URL=http://acala-graphql-engine:4401
      - ENDPOINT_URL=ws://acala-mandala-node:4444
      #- LOCAL_MODE=1
      #- SAFE_MODE=1
    command: yarn start

volumes:
  postgres:
```

Running gives this error over and over:
```
docker-compose -f ./docker-compose-acala.yml up
...
acala-eth-rpc-adapter-server    |   ------------------------------------------
acala-eth-rpc-adapter-server    |   ⚡️ running in production (standard) mode ⚡️
acala-eth-rpc-adapter-server    |   ------------------------------------------
acala-eth-rpc-adapter-server    | 
acala-mandala-node              | 2023-01-03 16:35:15 Accepting new connection 1/100
acala-eth-rpc-adapter-server    | 2023-01-03 16:35:15        API/INIT: RPC methods not decorated: evm_blockLimits
acala-eth-rpc-adapter-server    | Error: Check Graphql failed: FetchError: request to http://acala-graphql-engine:4401/ failed, reason: connect ECONNREFUSED 192.168.224.5:4401 (code=UNKNOWN_ERROR, version=bodhi.js/providers/2.5.3)
acala-eth-rpc-adapter-server    |     at Logger.makeError (/app/common/temp/node_modules/.pnpm/@ethersproject+logger@5.5.0/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
acala-eth-rpc-adapter-server    |     at Logger.throwError (/app/common/temp/node_modules/.pnpm/@ethersproject+logger@5.5.0/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
acala-eth-rpc-adapter-server    |     at SubqlProvider.checkGraphql (/app/eth-providers/lib/utils/subqlProvider.js:14:33)
acala-eth-rpc-adapter-server    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
acala-eth-rpc-adapter-server    |     at async start (/app/eth-rpc-adapter/src/index.ts:37:5) {
acala-eth-rpc-adapter-server    |   reason: 'Check Graphql failed: FetchError: request to http://acala-graphql-engine:4401/ failed, reason: connect ECONNREFUSED 192.168.224.5:4401',
acala-eth-rpc-adapter-server    |   code: 'UNKNOWN_ERROR'
```

**Comment by zjb0807** [comment]
your docker-compose.yml works for me.
After the node produces blocks, the services will work

**Comment by mcf-rocks** [comment]
hey zjb0807... so you didn't get this connection error:
```
acala-eth-rpc-adapter-server    | Error: Check Graphql failed: FetchError: request to http://acala-graphql-engine:4401/ failed, reason: connect ECONNREFUSED 192.168.224.5:4401 (code=UNKNOWN_ERROR, version=bodhi.js/providers/2.5.3)
```
I've run it all for 1 hour and it's still doing that.

I did it all again on fresh server and i don't get that error.

**Comment by zjb0807** [comment]
`- --indexer=http://subquery-node:4400` 
should be 
`- --indexer=http://acala-subquery-node:4401`

**Comment by zjb0807** [comment]
1. change the port mapping to `4400:3000`
```
  acala-subquery-node:
    image: acala/evm-subql:c65f9c3
    container_name: acala-subquery-node
    ports:
      - 4400:3000
```

2. change command in `acala-graphql-engine`:
`- --indexer=http://subquery-node:4400`
should be
`- --indexer=http://acala-subquery-node:3000`

docker logs -f acala-subquery-node
```
2023-01-03T21:48:36.297Z <subql-node> INFO Node started on port: 3000
```

the default define here: https://github.com/AcalaNetwork/bodhi.js/blob/e5f27cb6f2fa1a604e15a3d07f47e3ce995f0132/evm-subql/package.json#L13
